### ISSUE TITLE
Npm error when trying to create a salesforce changeset

### ISSUE THREAD

**Issue by BorjaLave** [microsoft/vscode-npm-scripts#105]
Hello, when I try to extract the differences between branchs to create a changeset with the differences for Salesforce sandbox a npm error is displayed.
The used command is: 
git diff master HEAD | force-dev-tool changeset create src --apiVersion 47.0 -d ./migration -f

The erros displayed is the next:
TypeError: Cannot read property 'type' of null
    at module.exports.Manifest.add (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\lib\manifest.js:57:20)    at C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:339:32
    at Array.forEach (<anonymous>)
    at DestroyableTransform._transform (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\lib\metadata-container.js:324:16)
    at DestroyableTransform.Transform._read (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Users\username\AppData\Roaming\npm\node_modules\force-dev-tool\node_modules\readable-stream\lib\_stream_readable.js:619:20)

Thanks,

**Comment by egamma** [comment]
This issue is not caused by this extension.
